spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/activity?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    name: activity
  activiti:
#    process-definition-location-prefix: classpath:processes/
#    process-definition-location-suffix: .bpmn20.xml
    history-level: full
    db-history-used: true
      # \u5173\u95ED\u81EA\u52A8\u90E8\u7F72
    deployment-mode: never-fail
      # \u5BF9\u6570\u636E\u5E93\u4E2D\u6240\u6709\u8868\u8FDB\u884C\u66F4\u65B0\u64CD\u4F5C\uFF0C\u5982\u679C\u8868\u4E0D\u5B58\u5728\uFF0C\u5219\u81EA\u52A8\u521B\u5EFA
      # create_drop\uFF1A\u542F\u52A8\u65F6\u521B\u5EFA\u8868\uFF0C\u5728\u5173\u95ED\u65F6\u5220\u9664\u8868\uFF08\u5FC5\u987B\u624B\u52A8\u5173\u95ED\u5F15\u64CE\uFF0C\u624D\u80FD\u5220\u9664\u8868\uFF09
      # drop-create\uFF1A\u542F\u52A8\u65F6\u5220\u9664\u539F\u6765\u7684\u65E7\u8868\uFF0C\u7136\u540E\u5728\u521B\u5EFA\u65B0\u8868\uFF08\u4E0D\u9700\u8981\u624B\u52A8\u5173\u95ED\u5F15\u64CE\uFF09
    database-schema-update: true
      # \u89E3\u51B3\u9891\u7E41\u67E5\u8BE2SQL\u95EE\u9898
    async-executor-activate: false

server:
  port: 9999
